# AIS identifier (MMSI)
int32 id
HelperLatLon lat_lon
# course over ground in degrees from CW from true north (float)
HelperHeading   cog
# speed over ground in kmph (float)
HelperSpeed   sog
# rate of turn in degrees per hour, positive for CW, negative for CCW (float)
HelperROT   rot
# width of the ship in meters (float)
HelperDimension width
# length of the ship in meters (float)
HelperDimension length
